### ISSUE TITLE
[Security] Potential Secret Leak

### ISSUE THREAD

**Issue by raima-zachariah** [plus3it/terraform-aws-codecommit-pr-reminders#412]
It has been noticed that while using plus3it/dependabot-terraform-action@p3-implementation your github_dependency_token 4224d33b8569bec8473980bb1bdb982639426a92 is present in plaintext. Please ensure that secrets are encrypted or not passed as plain text in github workflows.

**Comment by lorengordon** [comment]
@raima-zachariah Thanks for checking. It's a read-only token, and a holdover from the days before GitHub secrets was a thing, when this was the only way to authenticate!
